wandb_version: 1

alpha_max:
  value: 1
alpha_method:
  value: multi_factor
alpha_min:
  value: 0.05
alpha_quantity_temperature:
  value: 0.12946358270769556
alpha_quantity_threshold:
  value: 150
alpha_weight_consistency:
  value: 0.13791790395524467
alpha_weight_coverage:
  value: 0.1865520997162322
alpha_weight_diversity:
  value: 0.30498646635116977
alpha_weight_quantity:
  value: 0.3663539256639582
dropout:
  value: 0.1
early_stopping_metric:
  value: sampled_ndcg@10
early_stopping_min_delta:
  value: 0.002
early_stopping_patience:
  value: 10
embedding_dim:
  value: 64
fraction_train:
  value: 1
fusion_type:
  value: concat
local_epochs:
  value: 10
lr:
  value: 0.010867913863152563
mlp_hidden_dims:
  value: 128,64
model_type:
  value: bpr
num_negatives:
  value: 1
num_server_rounds:
  value: 100
prototype_momentum:
  value: 0.95
proximal_mu:
  value: 0.0012401886564724336
strategy:
  value: fedavg
weight_decay:
  value: 1.7181868125377202e-06
