wandb_version: 1

alpha_max:
  value: 0.95
alpha_method:
  value: data_quantity
alpha_min:
  value: 0.05
alpha_quantity_temperature:
  value: 0.13695658121558982
alpha_quantity_threshold:
  value: 50
alpha_weight_consistency:
  value: 0.17062783694361852
alpha_weight_coverage:
  value: 0.16863419775390798
alpha_weight_diversity:
  value: 0.4709192325598818
alpha_weight_quantity:
  value: 0.1417291389370779
dropout:
  value: 0.1
early_stopping_metric:
  value: sampled_ndcg@10
early_stopping_min_delta:
  value: 0.001
early_stopping_patience:
  value: 8
embedding_dim:
  value: 64
fraction_train:
  value: 1
fusion_type:
  value: gate
local_epochs:
  value: 15
lr:
  value: 0.048145403690473966
mlp_hidden_dims:
  value: 256,128
model_type:
  value: dual
num_negatives:
  value: 8
num_server_rounds:
  value: 100
prototype_momentum:
  value: 0.95
proximal_mu:
  value: 0.8815975208214193
strategy:
  value: fedprox
weight_decay:
  value: 1.528669516902573e-05
