wandb_version: 1

alpha_max:
  value: 0.95
alpha_method:
  value: multi_factor
alpha_min:
  value: 0.1
alpha_quantity_temperature:
  value: 0.07126582923487469
alpha_quantity_threshold:
  value: 150
alpha_weight_consistency:
  value: 0.2470856175490498
alpha_weight_coverage:
  value: 0.20922248673706667
alpha_weight_diversity:
  value: 0.1787554490532092
alpha_weight_quantity:
  value: 0.327190181540259
dropout:
  value: 0.1
early_stopping_metric:
  value: sampled_ndcg@10
early_stopping_min_delta:
  value: 0.001
early_stopping_patience:
  value: 10
embedding_dim:
  value: 64
fraction_train:
  value: 0.5
fusion_type:
  value: add
local_epochs:
  value: 5
lr:
  value: 0.00029834586552429047
mlp_hidden_dims:
  value: 512,256,128
model_type:
  value: dual
num_negatives:
  value: 8
num_server_rounds:
  value: 100
prototype_momentum:
  value: 0.8
proximal_mu:
  value: 0.5359807032407159
strategy:
  value: fedprox
weight_decay:
  value: 1.3271144512098744e-06
