wandb_version: 1

alpha_max:
  value: 1
alpha_method:
  value: multi_factor
alpha_min:
  value: 0.05
alpha_quantity_temperature:
  value: 0.13410646917121247
alpha_quantity_threshold:
  value: 100
alpha_weight_consistency:
  value: 0.16836118187058713
alpha_weight_coverage:
  value: 0.18937504682794087
alpha_weight_diversity:
  value: 0.43152146474591224
alpha_weight_quantity:
  value: 0.27299721384572917
dropout:
  value: 0.2
early_stopping_metric:
  value: sampled_ndcg@10
early_stopping_min_delta:
  value: 0.002
early_stopping_patience:
  value: 15
embedding_dim:
  value: 64
fraction_train:
  value: 1
fusion_type:
  value: gate
local_epochs:
  value: 5
lr:
  value: 0.0010740944765101849
mlp_hidden_dims:
  value: 512,256,128
model_type:
  value: bpr
num_negatives:
  value: 1
num_server_rounds:
  value: 100
prototype_momentum:
  value: 0.9
proximal_mu:
  value: 0.007482784588056052
strategy:
  value: fedprox
weight_decay:
  value: 1.1362436334370484e-05
