wandb_version: 1

alpha_max:
  value: 1
alpha_method:
  value: multi_factor
alpha_min:
  value: 0.1
alpha_quantity_temperature:
  value: 0.026045144284063168
alpha_quantity_threshold:
  value: 50
alpha_weight_consistency:
  value: 0.2789661134680128
alpha_weight_coverage:
  value: 0.2933342122185744
alpha_weight_diversity:
  value: 0.24453296116549336
alpha_weight_quantity:
  value: 0.11346108503477348
dropout:
  value: 0.2
early_stopping_metric:
  value: sampled_ndcg@10
early_stopping_min_delta:
  value: 0.0005
early_stopping_patience:
  value: 15
embedding_dim:
  value: 128
fraction_train:
  value: 1
fusion_type:
  value: concat
local_epochs:
  value: 10
lr:
  value: 0.01701629602590663
mlp_hidden_dims:
  value: 512,256,128
model_type:
  value: dual
num_negatives:
  value: 4
num_server_rounds:
  value: 100
prototype_momentum:
  value: 0.8
proximal_mu:
  value: 0.007611230622338691
strategy:
  value: fedavg
weight_decay:
  value: 0.00026272738392246227
