_wandb:
    value:
        cli_version: 0.23.1
        e:
            jxt6cirmj70h9t1cugwq7lesqz4atsfc:
                codePath: federated-adaptive-personalized-cf/scripts/run_wandb_sweep.py
                codePathLocal: scripts/run_wandb_sweep.py
                cpu_count: 24
                cpu_count_logical: 32
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "982240026624"
                        used: "751425089536"
                email: tranhgio15@gmail.com
                executable: /home/bes/miniconda3/envs/recsys_fl/bin/python
                git:
                    commit: f629de1f4c7da8bbc1807a6cadcfc235874365db
                    remote: git@github.com-vinh:TranhGio/Personalized-Federated-Learning-for-Privacy-Aware-Collaborative-Filtering-in-Recommender-Systems.git
                gpu: NVIDIA GeForce RTX 5090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-63741715-3e4c-5bcc-3255-600cb876e895
                host: bes-aimachine-02
                memory:
                    total: "67120590848"
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: /home/bes/Desktop/vinh/federated-learning/movie-recommendation-system/federated-adaptive-personalized-cf/scripts/run_wandb_sweep.py
                python: CPython 3.11.14
                root: /home/bes/Desktop/vinh/federated-learning/movie-recommendation-system/federated-adaptive-personalized-cf
                startedAt: "2026-01-22T18:01:57.350631Z"
                writerId: jxt6cirmj70h9t1cugwq7lesqz4atsfc
        m: []
        python_version: 3.11.14
        t:
            "3":
                - 2
                - 14
            "4": 3.11.14
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
alpha_max:
    value: 0.9
alpha_method:
    value: data_quantity
alpha_min:
    value: 0.2
alpha_quantity_temperature:
    value: 0.13671707572553918
alpha_quantity_threshold:
    value: 150
alpha_weight_consistency:
    value: 0.11109366787624768
alpha_weight_coverage:
    value: 0.29153696927453054
alpha_weight_diversity:
    value: 0.4845914112687685
alpha_weight_quantity:
    value: 0.4999817440356681
dropout:
    value: 0
early_stopping_metric:
    value: sampled_ndcg@10
early_stopping_min_delta:
    value: 0.002
early_stopping_patience:
    value: 10
embedding_dim:
    value: 64
fraction_train:
    value: 0.8
fusion_type:
    value: concat
local_epochs:
    value: 20
lr:
    value: 0.0008406252494230291
mlp_hidden_dims:
    value: 256,128
model_type:
    value: bpr
num_negatives:
    value: 8
num_server_rounds:
    value: 100
prototype_momentum:
    value: 0.8
proximal_mu:
    value: 0.239475139434928
strategy:
    value: fedavg
weight_decay:
    value: 3.55182354250074e-06
