_wandb:
    value:
        cli_version: 0.23.1
        e:
            g7ols0jbxc1i95g1vk59k5mow4zbgaso:
                codePath: federated-adaptive-personalized-cf/scripts/run_wandb_sweep.py
                codePathLocal: scripts/run_wandb_sweep.py
                cpu_count: 24
                cpu_count_logical: 32
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "982240026624"
                        used: "751424266240"
                email: tranhgio15@gmail.com
                executable: /home/bes/miniconda3/envs/recsys_fl/bin/python
                git:
                    commit: f629de1f4c7da8bbc1807a6cadcfc235874365db
                    remote: git@github.com-vinh:TranhGio/Personalized-Federated-Learning-for-Privacy-Aware-Collaborative-Filtering-in-Recommender-Systems.git
                gpu: NVIDIA GeForce RTX 5090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-63741715-3e4c-5bcc-3255-600cb876e895
                host: bes-aimachine-02
                memory:
                    total: "67120590848"
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: /home/bes/Desktop/vinh/federated-learning/movie-recommendation-system/federated-adaptive-personalized-cf/scripts/run_wandb_sweep.py
                python: CPython 3.11.14
                root: /home/bes/Desktop/vinh/federated-learning/movie-recommendation-system/federated-adaptive-personalized-cf
                startedAt: "2026-01-22T18:00:11.264361Z"
                writerId: g7ols0jbxc1i95g1vk59k5mow4zbgaso
        m: []
        python_version: 3.11.14
        t:
            "3":
                - 2
                - 14
            "4": 3.11.14
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
alpha_max:
    value: 1
alpha_method:
    value: multi_factor
alpha_min:
    value: 0.1
alpha_quantity_temperature:
    value: 0.04509758692098002
alpha_quantity_threshold:
    value: 100
alpha_weight_consistency:
    value: 0.16369722485346008
alpha_weight_coverage:
    value: 0.25326676462720055
alpha_weight_diversity:
    value: 0.4732147930507161
alpha_weight_quantity:
    value: 0.3566537772404986
dropout:
    value: 0.2
early_stopping_metric:
    value: sampled_ndcg@10
early_stopping_min_delta:
    value: 0.0005
early_stopping_patience:
    value: 8
embedding_dim:
    value: 256
fraction_train:
    value: 0.5
fusion_type:
    value: gate
local_epochs:
    value: 10
lr:
    value: 0.04661054116958595
mlp_hidden_dims:
    value: 512,256,128
model_type:
    value: dual
num_negatives:
    value: 8
num_server_rounds:
    value: 100
prototype_momentum:
    value: 0.8
proximal_mu:
    value: 0.011609073097918568
strategy:
    value: fedprox
weight_decay:
    value: 0.0003436450038126345
