_wandb:
    value:
        cli_version: 0.23.1
        e:
            o5s02r2cv7yuugig2oz4raegpxxdo8xe:
                args:
                    - --app
                    - .
                    - --num-supernodes
                    - "5"
                    - --backend-config
                    - '{"client-resources": {"num-cpus": 6, "num-gpus": 0.2}}'
                    - --run-config
                    - model-type='dual' fusion-type='concat'
                cpu_count: 24
                cpu_count_logical: 32
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "982240026624"
                        used: "616919302144"
                email: tranhgio15@gmail.com
                executable: /home/bes/miniconda3/envs/recsys_fl/bin/python3.11
                git:
                    commit: 29b8896b6967e8edea0150bba4b684f49064837b
                    remote: git@github.com-vinh:TranhGio/Personalized-Federated-Learning-for-Privacy-Aware-Collaborative-Filtering-in-Recommender-Systems.git
                gpu: NVIDIA GeForce RTX 5090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-63741715-3e4c-5bcc-3255-600cb876e895
                host: bes-aimachine-02
                memory:
                    total: "67124600832"
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: /home/bes/miniconda3/envs/recsys_fl/bin/flower-simulation
                python: CPython 3.11.14
                root: /home/bes/Desktop/vinh/federated-learning/movie-recommendation-system/federated-adaptive-personalized-cf
                startedAt: "2026-01-12T06:48:55.800206Z"
                writerId: o5s02r2cv7yuugig2oz4raegpxxdo8xe
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 30
                - 49
                - 53
            "2":
                - 1
                - 2
                - 3
                - 5
                - 30
                - 49
                - 53
            "3":
                - 2
                - 16
                - 61
                - 62
            "4": 3.11.14
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
alpha_max:
    value: 0.95
alpha_min:
    value: 0.1
alpha_quantity_temperature:
    value: 0.05
alpha_quantity_threshold:
    value: 100
dirichlet_alpha:
    value: 0.5
dropout:
    value: 0.1
embedding_dim:
    value: 128
fraction_train:
    value: 1
local_epochs:
    value: 10
lr:
    value: 0.005
model_type:
    value: dual
num_rounds:
    value: 50
prototype_momentum:
    value: 0.9
proximal_mu:
    value: 0.01
strategy:
    value: fedprox
weight_decay:
    value: 1e-05
