wandb_version: 1

alpha_max:
  value: 1
alpha_method:
  value: multi_factor
alpha_min:
  value: 0.1
alpha_quantity_temperature:
  value: 0.04509758692098002
alpha_quantity_threshold:
  value: 100
alpha_weight_consistency:
  value: 0.16369722485346008
alpha_weight_coverage:
  value: 0.25326676462720055
alpha_weight_diversity:
  value: 0.4732147930507161
alpha_weight_quantity:
  value: 0.3566537772404986
dropout:
  value: 0.2
early_stopping_metric:
  value: sampled_ndcg@10
early_stopping_min_delta:
  value: 0.0005
early_stopping_patience:
  value: 8
embedding_dim:
  value: 256
fraction_train:
  value: 0.5
fusion_type:
  value: gate
local_epochs:
  value: 10
lr:
  value: 0.04661054116958595
mlp_hidden_dims:
  value: 512,256,128
model_type:
  value: dual
num_negatives:
  value: 8
num_server_rounds:
  value: 100
prototype_momentum:
  value: 0.8
proximal_mu:
  value: 0.011609073097918568
strategy:
  value: fedprox
weight_decay:
  value: 0.0003436450038126345
