wandb_version: 1

alpha_max:
  value: 0.95
alpha_method:
  value: multi_factor
alpha_min:
  value: 0.05
alpha_quantity_temperature:
  value: 0.13640623637373434
alpha_quantity_threshold:
  value: 100
alpha_weight_consistency:
  value: 0.2523349456646485
alpha_weight_coverage:
  value: 0.26187893834759834
alpha_weight_diversity:
  value: 0.21505949538034447
alpha_weight_quantity:
  value: 0.4560083011693863
dropout:
  value: 0
early_stopping_metric:
  value: sampled_ndcg@10
early_stopping_min_delta:
  value: 0.002
early_stopping_patience:
  value: 10
embedding_dim:
  value: 128
fraction_train:
  value: 0.5
fusion_type:
  value: add
local_epochs:
  value: 15
lr:
  value: 0.018936790387284737
mlp_hidden_dims:
  value: 256,128
model_type:
  value: dual
num_negatives:
  value: 4
num_server_rounds:
  value: 100
prototype_momentum:
  value: 0.9
proximal_mu:
  value: 0.04947603673544324
strategy:
  value: fedprox
weight_decay:
  value: 4.8495485906237896e-05
