wandb_version: 1

alpha_max:
  value: 0.9
alpha_method:
  value: multi_factor
alpha_min:
  value: 0.05
alpha_quantity_temperature:
  value: 0.035235496115586074
alpha_quantity_threshold:
  value: 50
alpha_weight_consistency:
  value: 0.1272368701414866
alpha_weight_coverage:
  value: 0.27388893456697316
alpha_weight_diversity:
  value: 0.1833168277077483
alpha_weight_quantity:
  value: 0.29764043773827203
dropout:
  value: 0.1
early_stopping_metric:
  value: sampled_ndcg@10
early_stopping_min_delta:
  value: 0.0005
early_stopping_patience:
  value: 10
embedding_dim:
  value: 64
fraction_train:
  value: 0.8
fusion_type:
  value: add
local_epochs:
  value: 10
lr:
  value: 0.0005098711084357752
mlp_hidden_dims:
  value: 512,256,128
model_type:
  value: dual
num_negatives:
  value: 1
num_server_rounds:
  value: 100
prototype_momentum:
  value: 0.8
proximal_mu:
  value: 0.02738402308932685
strategy:
  value: fedprox
weight_decay:
  value: 3.7517405253495705e-05
