wandb_version: 1

alpha_max:
  value: 0.9
alpha_method:
  value: data_quantity
alpha_min:
  value: 0.2
alpha_quantity_temperature:
  value: 0.13671707572553918
alpha_quantity_threshold:
  value: 150
alpha_weight_consistency:
  value: 0.11109366787624768
alpha_weight_coverage:
  value: 0.29153696927453054
alpha_weight_diversity:
  value: 0.4845914112687685
alpha_weight_quantity:
  value: 0.4999817440356681
dropout:
  value: 0
early_stopping_metric:
  value: sampled_ndcg@10
early_stopping_min_delta:
  value: 0.002
early_stopping_patience:
  value: 10
embedding_dim:
  value: 64
fraction_train:
  value: 0.8
fusion_type:
  value: concat
local_epochs:
  value: 20
lr:
  value: 0.0008406252494230291
mlp_hidden_dims:
  value: 256,128
model_type:
  value: bpr
num_negatives:
  value: 8
num_server_rounds:
  value: 100
prototype_momentum:
  value: 0.8
proximal_mu:
  value: 0.239475139434928
strategy:
  value: fedavg
weight_decay:
  value: 3.55182354250074e-06
