wandb_version: 1

alpha_max:
  value: 0.95
alpha_method:
  value: multi_factor
alpha_min:
  value: 0.05
alpha_quantity_temperature:
  value: 0.05593386752456048
alpha_quantity_threshold:
  value: 100
alpha_weight_consistency:
  value: 0.28179932779202865
alpha_weight_coverage:
  value: 0.10884231816173344
alpha_weight_diversity:
  value: 0.2390786771719113
alpha_weight_quantity:
  value: 0.38219076888172376
dropout:
  value: 0
early_stopping_metric:
  value: sampled_ndcg@10
early_stopping_min_delta:
  value: 0.001
early_stopping_patience:
  value: 15
embedding_dim:
  value: 256
fraction_train:
  value: 0.5
fusion_type:
  value: gate
local_epochs:
  value: 10
lr:
  value: 0.00026351371495094474
mlp_hidden_dims:
  value: 256,128
model_type:
  value: bpr
num_negatives:
  value: 4
num_server_rounds:
  value: 100
prototype_momentum:
  value: 0.8
proximal_mu:
  value: 0.1056568889382746
strategy:
  value: fedavg
weight_decay:
  value: 3.305524974749876e-05
