wandb_version: 1

alpha_max:
  value: 1
alpha_method:
  value: multi_factor
alpha_min:
  value: 0.05
alpha_quantity_temperature:
  value: 0.02622396698472332
alpha_quantity_threshold:
  value: 50
alpha_weight_consistency:
  value: 0.2192729832843448
alpha_weight_coverage:
  value: 0.28579999273952694
alpha_weight_diversity:
  value: 0.4186528963983277
alpha_weight_quantity:
  value: 0.4825791414460283
dropout:
  value: 0.1
early_stopping_metric:
  value: sampled_ndcg@10
early_stopping_min_delta:
  value: 0.002
early_stopping_patience:
  value: 15
embedding_dim:
  value: 256
fraction_train:
  value: 0.8
fusion_type:
  value: concat
local_epochs:
  value: 20
lr:
  value: 0.006979129643968677
mlp_hidden_dims:
  value: 512,256,128
model_type:
  value: dual
num_negatives:
  value: 8
num_server_rounds:
  value: 100
prototype_momentum:
  value: 0.8
proximal_mu:
  value: 0.043672225633792784
strategy:
  value: fedavg
weight_decay:
  value: 4.0129169052712673e-05
