_wandb:
    value:
        cli_version: 0.23.1
        e:
            2f8guaz0uk6w925pu3x7wg89xt2jnjz6:
                args:
                    - --app
                    - .
                    - --num-supernodes
                    - "5"
                    - --run-config
                    - strategy="fedprox" proximal-mu=0.05 num-server-rounds=50 fraction-train=0.3 wandb-run-name="fedprox_mu0.05_r50_f0.3"
                cpu_count: 24
                cpu_count_logical: 32
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "982240026624"
                        used: "797887135744"
                email: tranhgio15@gmail.com
                executable: /home/bes/miniconda3/envs/recsys_fl/bin/python3.11
                git:
                    commit: e207ed3e9f78dcf039e23c890bf5cdbd772d236b
                    remote: git@github.com-vinh:TranhGio/Centralized-Recommender-Baselines-for-MovieLens.git
                gpu: NVIDIA GeForce RTX 5090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-63741715-3e4c-5bcc-3255-600cb876e895
                host: bes-aimachine-02
                memory:
                    total: "67124600832"
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: /home/bes/miniconda3/envs/recsys_fl/bin/flower-simulation
                python: CPython 3.11.14
                root: /home/bes/Desktop/vinh/federated-learning/movie-recommendation-system/federated-baseline-cf
                startedAt: "2025-12-28T15:48:17.199236Z"
                writerId: 2f8guaz0uk6w925pu3x7wg89xt2jnjz6
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 30
                - 49
                - 53
            "2":
                - 1
                - 2
                - 3
                - 5
                - 30
                - 49
                - 53
            "3":
                - 2
                - 13
                - 16
                - 61
                - 62
            "4": 3.11.14
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
alpha:
    value: 0.5
dropout:
    value: 0.1
embedding_dim:
    value: 128
fraction_train:
    value: 0.3
local_epochs:
    value: 5
lr:
    value: 0.005
model_type:
    value: basic
num_rounds:
    value: 50
proximal_mu:
    value: 0.05
strategy:
    value: fedprox
weight_decay:
    value: 1e-05
