_wandb:
    value:
        cli_version: 0.23.1
        e:
            mkdwhhatjg40zxxjvg9k49la8iib5bfo:
                args:
                    - --app
                    - .
                    - --num-supernodes
                    - "5"
                cpu_count: 24
                cpu_count_logical: 32
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "982240026624"
                        used: "621340696576"
                email: tranhgio15@gmail.com
                executable: /home/bes/miniconda3/bin/python3.13
                git:
                    commit: 29b8896b6967e8edea0150bba4b684f49064837b
                    remote: git@github.com-vinh:TranhGio/Personalized-Federated-Learning-for-Privacy-Aware-Collaborative-Filtering-in-Recommender-Systems.git
                gpu: NVIDIA GeForce RTX 5090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-63741715-3e4c-5bcc-3255-600cb876e895
                host: bes-aimachine-02
                memory:
                    total: "67124600832"
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: /home/bes/miniconda3/bin/flower-simulation
                python: CPython 3.13.5
                root: /home/bes/Desktop/vinh/federated-learning/movie-recommendation-system/federated-adaptive-personalized-cf
                startedAt: "2026-01-09T17:03:59.153957Z"
                writerId: mkdwhhatjg40zxxjvg9k49la8iib5bfo
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 30
                - 105
            "2":
                - 1
                - 30
                - 105
            "3":
                - 2
                - 16
                - 61
                - 62
            "4": 3.13.5
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
alpha_max:
    value: 0.95
alpha_min:
    value: 0.1
alpha_quantity_temperature:
    value: 0.05
alpha_quantity_threshold:
    value: 100
dirichlet_alpha:
    value: 0.5
dropout:
    value: 0.1
embedding_dim:
    value: 128
fraction_train:
    value: 1
local_epochs:
    value: 5
lr:
    value: 0.005
model_type:
    value: bpr
num_rounds:
    value: 10
prototype_momentum:
    value: 0.9
proximal_mu:
    value: 0.01
strategy:
    value: fedavg
weight_decay:
    value: 1e-05
